### ISSUE TITLE
TypeError: b64UrlString.replace is not a function

### ISSUE THREAD

**Issue by Moogamouth** [ArweaveTeam/arweave-js#186]
```js
await arweave.createTransaction({data: "data"});
```
Returns an error:
```
 b64UrlString = b64UrlString.replace(/\-/g, "+").replace(/\_/g, "/");
                                ^

TypeError: b64UrlString.replace is not a function
    at b64UrlDecode (C:\Users\isaac\node_modules\arweave\node\lib\utils.js:91:33)
    at Object.b64UrlToBuffer (C:\Users\isaac\node_modules\arweave\node\lib\utils.js:72:45)
    at Tag.get (C:\Users\isaac\node_modules\arweave\node\lib\transaction.js:54:33)
    at C:\Users\isaac\node_modules\arweave\node\lib\transaction.js:188:25
    at Array.map (<anonymous>)
    at Transaction.getSignatureData (C:\Users\isaac\node_modules\arweave\node\lib\transaction.js:186:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Arweave.createTransaction (C:\Users\isaac\node_modules\arweave\node\common.js:99:9)
    at async archiveSource (C:\Users\isaac\Documents\Chivify\index.js:15:95)
```

**Comment by rosmcmahon** [comment]
can you give more detail in order to reproduce this? it's working fine in all other tests and apps.
usually this error occurs when a function has an undefined input argument.
