### ISSUE TITLE
ReferenceError: Headers is not defined

### ISSUE THREAD

**Issue by vird** [ArweaveTeam/arweave-js#200]
https://gist.github.com/vird/c5e5a0812d8756f3a2559052c38a3e11
```
/data/nodejs/experiments/virdpool_hdwallet_rsa_test2/node_modules/arweave/node/lib/api.js:46
        const headers = new Headers(init?.headers || {});
                        ^

ReferenceError: Headers is not defined
    at Api.request (/data/nodejs/experiments/virdpool_hdwallet_rsa_test2/node_modules/arweave/node/lib/api.js:46:25)
    at Api.get (/data/nodejs/experiments/virdpool_hdwallet_rsa_test2/node_modules/arweave/node/lib/api.js:30:27)
    at Transactions.getTransactionAnchor (/data/nodejs/experiments/virdpool_hdwallet_rsa_test2/node_modules/arweave/node/transactions.js:51:25)
    at Arweave.createTransaction (/data/nodejs/experiments/virdpool_hdwallet_rsa_test2/node_modules/arweave/node/common.js:88:59)
    at /data/nodejs/experiments/virdpool_hdwallet_rsa_test2/use.js:78:35
    at Object.<anonymous> (/data/nodejs/experiments/virdpool_hdwallet_rsa_test2/use.js:105:3)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)

```

**Comment by rosmcmahon** [comment]
does this help? https://github.com/ArweaveTeam/arweave-js/releases/tag/v1.12.4

**Comment by vird** [comment]
I was using 1.12.7. 1.12.4 same error

**Comment by rosmcmahon** [comment]
What version of NodeJS are you using @vird ?

**Comment by vird** [comment]
v16.19.0

**Comment by rosmcmahon** [comment]
Thanks for the suggestion, I'll look into it 🙂

**Comment by juanleondev** [comment]
Hi @rosmcmahon , I'm trying to use the package with a Firebase Cloud function and I'm getting the same error 😞 
`Headers is not defined`
I'm adding --experimental-fetch in this way:

process.env.NODE_OPTIONS = '--experimental-fetch --no-warnings';

Complete code: https://gist.github.com/juanleondev/486496329bca14bdf9775a4a439decf9

**Comment by rosmcmahon** [comment]
> Hi @rosmcmahon , I'm trying to use the package with a Firebase Cloud function and I'm getting the same error 😞 `Headers is not defined` I'm adding --experimental-fetch in this way:
> 
> process.env.NODE_OPTIONS = '--experimental-fetch --no-warnings';
> 
> Complete code: https://gist.github.com/juanleondev/486496329bca14bdf9775a4a439decf9

yes, unfortunately those options need to already be set when nodejs is started, otherwise we would have already been doing that in the library.

if you cannot set node startup arguments in this way, it would be easiest to choose nodejs v18+ [https://firebase.google.com/docs/functions/manage-functions?gen=2nd#set_nodejs_version](https://firebase.google.com/docs/functions/manage-functions?gen=2nd#set_nodejs_version)

**Comment by juanleondev** [comment]
@rosmcmahon Thank you very much! Updating to Node18 works 💯

**Comment by 7kms** [comment]
update to the latest node and the issue missed
node version:
v20.5.0

**Comment by rosmcmahon** [comment]
> update to the latest node and the issue missed

sorry @7kms, what does this mean?
