### ISSUE TITLE
[BUG] Arweave-js not working with Svelte/Sapper

### ISSUE THREAD

**Issue by martonlederer** [ArweaveTeam/arweave-js#49]
Hey, when I import Arweave from arweave-js with Svelte/Sapper, I get the errors pasted below.
My code:
```ts
import Arweave from "arweave/web"; // the compiler fails here

const client = new Arweave({
  host: "arweave.net",
  port: 443,
  protocol: "https",
  timeout: 20000,
});
```

### The log/error:
Client (Svelte): 
```sh
Circular dependency: node_modules\arweave\web\common.js -> node_modules\arweave\web\transactions.js -> node_modules\arweave\web\lib\transaction.js -> node_modules\arweave\web\lib\deepHash.js -> node_modules\arweave\web\common.js
```
Server (Sapper with polka):
```sh
✗ server
Unexpected token (Note that you need @rollup/plugin-json to import JSON files)
1: {
2:   "name": "axios",
           ^
3:   "version": "0.18.1",
4:   "description": "Promise based HTTP client for the browser and node.js",
internal/modules/cjs/loader.js:330
      throw err;
      ^

Error: Cannot find module 'C:\Users\user\Desktop\Node\coinary-frontend\node_modules\arweave\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:322:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:683:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\user\Desktop\Node\coinary-frontend\__sapper__\dev\server\server.js:10:1)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32) {
  code: 'MODULE_NOT_FOUND',
  path: 'C:\\Users\\user\\Desktop\\Node\\coinary-frontend\\node_modules\\arweave\\package.json',
  requestPath: 'arweave'
}
> Server crashed
```
Full log from terminal: 
```sh
src\stores\keyfileStore.js changed. rebuilding...
• client
Circular dependency: node_modules\arweave\web\common.js -> node_modules\arweave\web\transactions.js -> node_modules\arweave\web\lib\transaction.js -> node_modules\arweave\web\lib\deepHash.js -> node_modules\arweave\web\common.js
Circular dependency: node_modules\arweave\web\common.js -> node_modules\arweave\web\transactions.js -> node_modules\arweave\web\lib\transaction.js -> node_modules\arweave\web\lib\deepHash.js ->  C:\Users\user\Desktop\Node\xy-frontend\node_modules\arweave\web\common.js?commonjs-proxy -> node_modules\arweave\web\common.js
Circular dependency: node_modules\arweave\web\common.js -> node_modules\arweave\web\transactions.js -> node_modules\arweave\web\lib\transaction.js -> node_modules\arweave\web\lib\merkle.js -> node_modules\arweave\web\common.js
✔ service worker (1.2s)
✗ server
Unexpected token (Note that you need @rollup/plugin-json to import JSON files)
1: {
2:   "name": "axios",
           ^
3:   "version": "0.18.1",
4:   "description": "Promise based HTTP client for the browser and node.js",
internal/modules/cjs/loader.js:330
      throw err;
      ^

Error: Cannot find module 'C:\Users\user\Desktop\Node\xy-frontend\node_modules\arweave\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:322:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:683:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\user\Desktop\Node\xy-frontend\__sapper__\dev\server\server.js:10:1)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32) {
  code: 'MODULE_NOT_FOUND',
  path: 'C:\\Users\\user\\Desktop\\Node\\xy-frontend\\node_modules\\arweave\\package.json',
  requestPath: 'arweave'
}
> Server crashed
```

**Comment by DougAnderson444** [comment]
Do you have `@rollup/plugin-json` installed and imported in rollup.config?

**Comment by rosmcmahon** [comment]
@martonlederer did you get anywhere with this issue? can i close it?

**Comment by martonlederer** [comment]
Hey @rosmcmahon no longer relevant, feel free to close

**Comment by rosmcmahon** [comment]
thanks Marton!
